### ISSUE TITLE
Receiving a Divide by zero error everytime 

### ISSUE THREAD

**Issue by anishLearnsToCode** [shameempk/fast_seg#1]
Everytime I run the program with `python fast_seg.py -i lenna.png` there is a prompt and I mark the bg and fg and then press `esc`. After that it throws the following error everytime irrespecctive of how i mark. I have also tried it with other images.

```text
 File "fast_seg.py", line 389, in <module>
    main()
  File "fast_seg.py", line 337, in main
    G = gen_graph(I_lab, SP_list, hist_ob, hist_bg)
  File "fast_seg.py", line 230, in gen_graph
    pr_bg = int(hist_bg[l_i, a_i, b_i]) / hist_bg_sum
ZeroDivisionError: division by zero
```

Cold you plese help me out as I am also conducting research in this topic and woud love to use this code and cite this. Let me know if I'm doing something wrong or maybe there's some mistake in the algorithm.

**Comment by shameempk** [comment]
I haven't looked back at this code for a long time. Give me two days. I'll help you if I can.

**Comment by anishLearnsToCode** [comment]
Okay, thanks. I would be pretty greatful ifyou can help me out. Am actively working in this field and haven't been able to find a single good working example of user assisted segmentation.

**Comment by shameempk** [comment]
Provide me some information.
How are you running this project? Venv? Which version of Python? Are you using the library versions as per requirements.txt?

**Comment by anishLearnsToCode** [comment]
I am using `python 3.8.3` and yes i created a virtual environment using `venv`. I also installed all dependencies using `pip install -4 requirements.txt`. After installing dependencies there was no error in importing libraries such as numpy, cv2 etc. I added my own photo. I used the standard 512x512 __lenna__ photo and ran the program with `python fast_seg.py -i lenna.png` and then a popup window appeared with my photo and i marked seeds. Another question, how are we supposed to mark bg and fg seeds, because there is no seperate option for that. 

After marking seeds I pressed `esc` and then git the above error.

**Comment by shameempk** [comment]
I have modified requirements.txt to contain all the version numbers as well. This shouldn't solve your issue.

>Another question, how are we supposed to mark bg and fg seeds, because there is no seperate option for that.

From readme:
Will provide a minimal GUI to mark the seed pixels. While marking, switching between "background" and "object" pixels are done using keys 'b' and 'o' respectively. By default GUI initializes in object mode. Object is marked with "red" markings and Background with "blue".

I think your problem of divided by zero has something to do with this marking. May be you haven't marked background at all. Try this and let me know.

**Comment by anishLearnsToCode** [comment]
Okay, I was making a mistake and not marking the background seeds using `b`, but after doing that now. It is working. Thank you very much. Also another question. In the output theer are 4 outputs

(1, 1): Seems like the origional mage
(2, 2): Seems like the segmented image

Can you tell mw what are the (1, 2) and (2, 1) images for? What do they represent?

**Comment by anishLearnsToCode** [comment]
Alright I did some further reading and I have figured out what the images at coordinates __(1, 2)__ and __(2, 1)__ are. Just one more question (sorry for pestering). How ca I increase the number of centroids in the algorithms, so that their ae more smaller regions and the results of segmentation can be improved?

**Comment by shameempk** [comment]
IIRC I have used opencv library to generate superpixels. I would suggest you to read opencv python documentation. If algorithm supports that, there must be options to do that as an argument or something.
